<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseAppHost>true</UseAppHost>
    <StartupObject>LatexVault.EntryPoint</StartupObject>
    <ApplicationIcon />
    <RootNamespace>LatexVault</RootNamespace>
    <AssemblyName>LatexVault</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Docnet.Core" Version="2.6.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Tex-Mode.xshd">
      <LogicalName>LatexVault.Assets.Tex-Mode.xshd</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Library\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
